### PR TITLE
Add CI and test with JUnit

### PR DESCRIPTION
**Pull request by kevinthegreat1**
Added CI and test with JUnit.
Also updated from gradle 7.4 to 8.7. (All the wrapper and gradlew changes are done automatically with `./gradlew wrapper --gradle-version 8.7`.)  
See test [here](https://github.com/kevinthegreat1/RepoParser/actions/runs/8943918404/job/24569680184).

### CODE REVIEW

**Comment by kevinthegreat1** [comment]
GitHub doesn't like how I moved the test file, but you can compare the deleted `TestMain` with the new one to see the diff. I just replaced everything with assertions. Hope this helps.

**Comment by kevinthegreat1** [comment]
Closes #4

**Comment by lineargraph** [comment]
Rebased this so i can have the gradle wrapper validation action run on this. I am not too sure about those tests. Some of those seem very fragile keeping in mind future updates (for example max fairy souls will certainly change at some point). Maybe this can be helped by pinning the repo commit? I also think those tests should be split up into multiple functions.

**Comment by kevinthegreat1** [comment]
Done

**Review by lineargraph — APPROVED** [review]

**Pull request merged**
